# Generated by Django 2.0 on 2018-04-17 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade_it', '0002_auto_20180417_2337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='customers',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='employees',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='regions',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='warehouses',
            options={'managed': True},
        ),
    ]
