# Generated by Django 2.0 on 2018-04-17 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade_it', '0005_auto_20180417_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='cust_products',
        ),
    ]
