# Generated by Django 2.0 on 2018-04-17 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade_it', '0007_auto_20180417_2345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehouses',
            options={'managed': True},
        ),
    ]
