# Generated by Django 2.0 on 2018-04-17 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_it', '0008_auto_20180417_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='cust_prods',
            field=models.ManyToManyField(to='trade_it.Products'),
        ),
    ]
