# Generated by Django 2.0 on 2018-04-18 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_it', '0009_customers_cust_prods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='region',
            field=models.ForeignKey(blank=True, db_column='region', null=True, on_delete=django.db.models.deletion.CASCADE, to='trade_it.Regions'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user', null=True, on_delete=django.db.models.deletion.CASCADE, to='trade_it.Users'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='region',
            field=models.ForeignKey(db_column='region', on_delete=django.db.models.deletion.CASCADE, to='trade_it.Regions'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='warehouse',
            field=models.ForeignKey(db_column='warehouse', on_delete=django.db.models.deletion.CASCADE, to='trade_it.Warehouses'),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(db_column='category', on_delete=django.db.models.deletion.CASCADE, to='trade_it.Categories'),
        ),
        migrations.AlterField(
            model_name='products',
            name='user',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to='trade_it.Users'),
        ),
        migrations.AlterField(
            model_name='products',
            name='warehouse',
            field=models.ForeignKey(db_column='warehouse', on_delete=django.db.models.deletion.CASCADE, to='trade_it.Warehouses'),
        ),
        migrations.AlterField(
            model_name='warehouses',
            name='manager',
            field=models.ForeignKey(db_column='manager', on_delete=django.db.models.deletion.CASCADE, to='trade_it.Employees'),
        ),
        migrations.AlterField(
            model_name='warehouses',
            name='region',
            field=models.ForeignKey(db_column='region', on_delete=django.db.models.deletion.CASCADE, to='trade_it.Regions'),
        ),
    ]
