# Generated by Django 2.0 on 2018-04-21 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_it', '0011_auto_20180418_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouses',
            name='manager',
            field=models.ForeignKey(db_column='manager', default=None, on_delete=django.db.models.deletion.CASCADE, to='trade_it.Employees'),
        ),
    ]
