# Generated by Django 2.0 on 2018-04-23 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_it', '0020_auto_20180423_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='trade_it.Users'),
        ),
    ]
