# Generated by Django 2.0 on 2018-04-24 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_it', '0023_auto_20180423_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='customer',
            field=models.ForeignKey(blank=True, db_column='customer', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='trade_it.Customers'),
        ),
    ]
