# Generated by Django 2.0 on 2018-04-24 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade_it', '0026_auto_20180424_0108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='user',
        ),
    ]
